# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rasacore', '0018_auto_20171117_1226'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='intentactions',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='intentactions',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=1, editable=False),
            preserve_default=False,
        ),
    ]
