# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rasacore', '0019_auto_20171119_0902'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='intentactionsresponses',
            options={'ordering': ('-created_at',), 'verbose_name': 'Action response', 'verbose_name_plural': 'Action responses'},
        ),
        migrations.AlterModelOptions(
            name='intents',
            options={'ordering': ('-created_at',), 'verbose_name': 'Intent', 'verbose_name_plural': 'Intents'},
        ),
        migrations.AlterModelOptions(
            name='intentusersays',
            options={'ordering': ('-created_at',), 'verbose_name': 'Intent User Say', 'verbose_name_plural': 'Intent User Says'},
        ),
        migrations.AlterModelOptions(
            name='intentusersaysentities',
            options={'ordering': ('-created_at',), 'verbose_name': 'User Says Entity', 'verbose_name_plural': 'User Says Entities'},
        ),
        migrations.AlterModelOptions(
            name='responsebuttons',
            options={'ordering': ('-created_at',), 'verbose_name': 'Button', 'verbose_name_plural': 'Buttons'},
        ),
        migrations.AlterModelOptions(
            name='stories',
            options={'ordering': ('-created_at',), 'verbose_name': 'Story', 'verbose_name_plural': 'Stories'},
        ),
        migrations.AddField(
            model_name='intentactions',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='intentactions',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='intentactionsresponses',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='intentactionsresponses',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='intents',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='intents',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='intentusersays',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='intentusersays',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='intentusersaysentities',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='intentusersaysentities',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='responsebuttons',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='responsebuttons',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='stories',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='stories',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='training',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='training',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
